version: '3'
services:
 nginx:
  image: nginx:latest
  ports:
   - "80:80"
  volumes:
   - ./nginx:/etc/nginx/conf.d
   - static-data:/static
   - media-data:/media
  depends_on:
   - web
 web:
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
   - static-data:/server/static
   - media-data:/server/media
volumes:
 static-data:
 media-data: