version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/server
      - ./static:/server/static
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./static:/server/static
      - ./nginx:/etc/nginx/nginx.conf
    depends_on:
      - web
