# Generated by Django 4.0.3 on 2022-04-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='celebrities',
        ),
    ]
