# Generated by Django 4.0.3 on 2022-04-06 08:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='')),
                ('job', models.CharField(max_length=15)),
                ('MBTI', models.CharField(max_length=7)),
                ('nationality', models.CharField(max_length=15)),
                ('introduction', models.TextField()),
                ('body_spec', models.JSONField()),
                ('education', models.CharField(max_length=15)),
                ('wealth', models.CharField(max_length=15)),
                ('spouse', models.CharField(max_length=15)),
                ('children', models.JSONField()),
                ('age', models.PositiveIntegerField()),
                ('birthday', models.CharField(max_length=15)),
                ('deceased_at', models.CharField(max_length=15)),
                ('routines', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), size=8)),
            ],
        ),
    ]
