# Generated by Django 4.0.3 on 2022-04-18 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CelebrityRoutines',
            new_name='CelebrityRoutine',
        ),
    ]
