# Generated by Django 4.0.3 on 2022-04-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='wise_saying',
            field=models.CharField(default='', max_length=31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='education',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='wealth',
            field=models.CharField(max_length=65),
        ),
    ]
