# Generated by Django 4.0.3 on 2022-04-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0002_rename_celebrityroutines_celebrityroutine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrity',
            name='children',
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='wealth',
            field=models.TextField(),
        ),
    ]
