# Generated by Django 4.0.3 on 2022-04-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0002_celebrity_wise_saying_alter_celebrity_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='birthday',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='children',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='deceased_at',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='education',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='spouse',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='wealth',
            field=models.CharField(max_length=63),
        ),
    ]
