# Generated by Django 4.0.3 on 2022-04-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0003_remove_celebrity_children_alter_celebrity_wealth'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='children',
            field=models.TextField(default='d'),
            preserve_default=False,
        ),
    ]
