# Generated by Django 4.0.3 on 2022-04-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0004_celebrity_english_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelebrityJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('background_color', models.CharField(choices=[('Ma', 'Main'), ('Su', 'Sub'), ('Bl', 'Black'), ('Gy1', 'Gray1'), ('Gy2', 'Gray2'), ('R1', 'Red1'), ('R2', 'Red2'), ('Ne', 'Negative'), ('Gr1', 'Green1'), ('Gr2', 'Green2'), ('P1', 'Pink1'), ('P2', 'Pink2')], max_length=3)),
                ('text_color', models.CharField(choices=[('Ma', 'Main'), ('Su', 'Sub'), ('Bl', 'Black'), ('Gy1', 'Gray1'), ('Gy2', 'Gray2'), ('R1', 'Red1'), ('R2', 'Red2'), ('Ne', 'Negative'), ('Gr1', 'Green1'), ('Gr2', 'Green2'), ('P1', 'Pink1'), ('P2', 'Pink2')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='job',
        ),
        migrations.AddField(
            model_name='celebrity',
            name='job',
            field=models.ManyToManyField(to='celebrities.celebrityjob'),
        ),
    ]
