# Generated by Django 4.0.3 on 2022-04-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0005_celebritytmi_remove_celebrity_tmi_celebrity_tmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebritytmi',
            name='content',
            field=models.CharField(max_length=32),
        ),
    ]
