# Generated by Django 4.0.3 on 2022-04-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0005_celebrityjob_remove_celebrity_job_celebrity_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrityjob',
            name='background_color',
            field=models.CharField(choices=[('soul_main', 'Main'), ('soul_sub', 'Sub'), ('soul_black', 'Black'), ('soul_gray1', 'Gray1'), ('soul_gray2', 'Gray2'), ('soul_red1', 'Red1'), ('soul_red2', 'Red2'), ('Ne', 'Negative'), ('Gr1', 'Green1'), ('Gr2', 'Green2'), ('P1', 'Pink1'), ('P2', 'Pink2')], max_length=31),
        ),
        migrations.AlterField(
            model_name='celebrityjob',
            name='text_color',
            field=models.CharField(choices=[('soul_main', 'Main'), ('soul_sub', 'Sub'), ('soul_black', 'Black'), ('soul_gray1', 'Gray1'), ('soul_gray2', 'Gray2'), ('soul_red1', 'Red1'), ('soul_red2', 'Red2'), ('Ne', 'Negative'), ('Gr1', 'Green1'), ('Gr2', 'Green2'), ('P1', 'Pink1'), ('P2', 'Pink2')], max_length=31),
        ),
    ]
