# Generated by Django 4.0.3 on 2022-04-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0006_alter_celebrityjob_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrityjob',
            name='background_color',
            field=models.CharField(choices=[('soulMain', 'Main'), ('soulSub', 'Sub'), ('soulBlack', 'Black'), ('soulGray1', 'Gray1'), ('soulGray2', 'Gray2'), ('soulRed1', 'Red1'), ('soulRed2', 'Red2'), ('soulNegative', 'Negative'), ('soulGreen1', 'Green1'), ('soulGreen2', 'Green2'), ('soulPink1', 'Pink1'), ('soulPink2', 'Pink2')], max_length=31),
        ),
        migrations.AlterField(
            model_name='celebrityjob',
            name='text_color',
            field=models.CharField(choices=[('soulMain', 'Main'), ('soulSub', 'Sub'), ('soulBlack', 'Black'), ('soulGray1', 'Gray1'), ('soulGray2', 'Gray2'), ('soulRed1', 'Red1'), ('soulRed2', 'Red2'), ('soulNegative', 'Negative'), ('soulGreen1', 'Green1'), ('soulGreen2', 'Green2'), ('soulPink1', 'Pink1'), ('soulPink2', 'Pink2')], max_length=31),
        ),
    ]
