# Generated by Django 4.0.3 on 2022-04-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0007_alter_celebrityjob_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrity',
            name='job',
        ),
        migrations.AddField(
            model_name='celebrity',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='celebrities.celebrityjob'),
            preserve_default=False,
        ),
    ]
